"""ToolBackend — the pluggable boundary that lets OpenClaw run standalone or with Django.

Read tools have no side effects. Write/action tools DO, and are routed through the
ToolExecutor (executor.py) which enforces capability gating, idempotency, and audit.
A backend just implements storage/retrieval/publishing; it does NOT decide gating.
"""
from __future__ import annotations

from typing import Protocol

from .schemas import Customer, Draft, KBChunk, NormalizedMessage


class ToolBackend(Protocol):
    # ----- read tools (safe) -----
    def get_customer(self, external_id: str) -> Customer | None: ...
    def get_conversation(self, thread_key: str) -> list[dict]: ...
    def search_kb(self, query: str, intent: str | None = None, k: int = 5) -> list[KBChunk]: ...
    def lookup_subscription(self, customer_id: str) -> dict | None: ...
    def refund_eligibility(self, customer_id: str, order_id: str) -> dict: ...

    # ----- write / action tools (gated by the executor, not here) -----
    def save_conversation(self, msg: NormalizedMessage, *, idempotency_key: str) -> str: ...
    def save_draft(self, thread_key: str, draft: Draft, *, idempotency_key: str) -> str: ...
    def publish_reply(self, thread_key: str, text: str, *, idempotency_key: str) -> str: ...
    def route_to_human(self, thread_key: str, intent: str, reason: str) -> None: ...
    def gate_mode(self, action: str, *, channel: str, intent: str) -> str: ...
    def log_tool_call(self, record: dict) -> None: ...

    # ----- review queue (human approval loop) -----
    def list_pending_drafts(self) -> list[dict]: ...
    def get_draft(self, draft_id: str) -> dict | None: ...
    def resolve_draft(
        self, draft_id: str, *, status: str, final_text: str = "",
        review_note: str = "", edit_diff: str = "",
    ) -> None: ...
